services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=@a123456
    command:
      - redis-server
      - --requirepass
      - '@a123456'
      - --dir
      - /bitnami/redis/data
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/bitnami/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "@a123456", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
      
volumes:
  redis-data: